# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 15:02
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netpages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['article_cate', '-commit_date']},
        ),
        migrations.AlterField(
            model_name='article',
            name='article_content',
            field=ckeditor.fields.RichTextField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_img',
            field=models.ImageField(default='.\\media\\pic\\demo.png', upload_to='.\\media\\pic'),
        ),
    ]
