# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netpages', '0002_auto_20170515_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top3p',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('i', models.IntegerField()),
                ('img', models.ImageField(default='.\\media\\pic\\demo.png', upload_to='.\\media\\pic')),
            ],
            options={
                'ordering': ['-i'],
            },
        ),
    ]
