# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netpages', '0003_top3p'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_author',
            field=models.CharField(default='QingLang', max_length=30),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_img',
            field=models.ImageField(default='.\\media\\pic\\demo.png', upload_to='pic'),
        ),
        migrations.AlterField(
            model_name='top3p',
            name='img',
            field=models.ImageField(default='.\\media\\pic\\demo.png', upload_to='pic'),
        ),
    ]
